### ISSUE TITLE
Build with AGP 8.0 leads to crashes in runtime

### ISSUE THREAD

**Issue by osipxd** [osipxd/encrypted-datastore#22]
If I build the library with AGP 8.0+, I get a runtime exception:
```java
java.lang.NoClassDefFoundError: Failed resolution of: Lio/github/osipxd/datastore/encrypted/PreferenceDataStoreHack;
    at io.github.osipxd.datastore.encrypted.EncryptedPreferenceDataStoreKt.(EncryptedPreferenceDataStore.kt:52)
    at io.github.osipxd.datastore.encrypted.EncryptedPreferenceDataStoreKt.getPreferencesSerializer(EncryptedPreferenceDataStore.kt:52)
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.github.osipxd.datastore.encrypted.PreferenceDataStoreHack" on path: DexPathList[[zip file "/data/app/~~xBo6035bH4FmFe4ueiv11g==/io.github.osipxd.security.datastore.preferences.test-llxPf-1rR2bKEpw4YiDFHA==/base.apk"],nativeLibraryDirectories=[/data/app/~~xBo6035bH4FmFe4ueiv11g==/io.github.osipxd.security.datastore.preferences.test-llxPf-1rR2bKEpw4YiDFHA==/lib/arm64, /system/lib64, /system_ext/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
```
As a workaround, I'll stay on AGP 7.4.2 for now.

There was a similar bug in AGP 4.2, so maybe it's a regression: [b/187353303](https://issuetracker.google.com/issues/187353303)

**Comment by osipxd** [comment]
The problem was because of the `encrypted-datastore-internal-visibility-hack` module configuration. Fixed by #25
